name: ome2-validator-devcontainer

services:
  validator:
    image: eurogeographics/ome2-validator
    build:
      context: ..
      dockerfile: Dockerfile
    
    volumes:
      - ..:/workspace
      #- ./resolv.google.conf:/etc/resolv.conf  # Uncomment to override host's DNS config
    working_dir: /workspace

    extra_hosts:
      - host.docker.internal:host-gateway
