from dataclasses import dataclass
from models import AbstractModel

@dataclass
class ValidationTask(AbstractModel):
    """Dataclass for storing validation tasks in the database.

    Attributes:
        task_id (int): The id of the task, automatically generated by the database for new tasks.
        name (str): The name of this task.
    """
    task_id: int
    name: str
