from dataclasses import dataclass
from models import AbstractModel
import datetime

@dataclass
class ValidationLogging(AbstractModel):
    """Dataclass for storing log-records in the database.

    Attributes:
        log_id (int): The id of this log-record, automatically generated by the database on insertion.
        timestamp (date): The timestamp.
        run_id (int): The corresponding run_id.
        severity (str): The severity.
        message (str): The actual log-message.
        module (str): The module from which this log-message was created.
    """
    log_id: int
    timestamp: datetime.date
    run_id : int
    severity: str
    message: str
    module: str
